name: 'Notify Slack'

description: 'POST Github Information to slack'

branding:
  icon: 'mail'
  color: 'green'

inputs:
  url: # slack webhook url
    description: 'slack webhook URL'
    required: true
    default: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'

  token: # slack API token
    description: 'slack API token'
    required: true
    default: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

outputs:
  success: # id of output
    description: 'Was the POST successful?'

runs:
  using: 'node16'
  main: 'dist/index.js'
